name: 'Pages Jekyll'
description: 'A simple GitHub Action for producing Jekyll build artifacts compatible with GitHub Pages'
inputs:
  source:
    description: 'Directory where the source files reside.'
    required: false
    default: ./
  destination:
    description: 'Output directory of the build. Although it can be nested inside the source, it cannot be the same as the source directory.'
    required: false
    default: ./_site
  verbose: # TODO: Should we support verbose output in GA?
    description: 'Verbose output'
    required: false
    default: '1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.source }}
    - ${{ inputs.destination }}
    - ${{ inputs.verbose }}

