#!/bin/bash

cd /src/gh/pages-gem

SOURCE_DIRECTORY=${GITHUB_WORKSPACE}/$INPUT_SOURCE
DESTINATION_DIRECTORY=${GITHUB_WORKSPACE}/$INPUT_DESTINATION

jekyll build --verbose --source $SOURCE_DIRECTORY --destination $DESTINATION_DIRECTORY
