dist: trusty
sudo: false

language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

node_js:
  - 7

before_install:
  - rvm install 2.3.4

script:
  - npm test
  - npm run lighthouse

env:
  global:
    - ATOM_ACCESS_TOKEN=da809a6077bb1b0aa7c5623f7b2d5f1fec2faae4

branches:
  only:
    - gh-pages

addons:
  chrome: beta
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

env:
  CXX=g++-4.8
