name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test-simple:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: simple
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test"

  test-readme:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: readme
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test"

  test-mojombo:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: mojombo
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test"

  test-themes:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: themes
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test"

  test-jekyll-include-cache:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: jekyll-include-cache
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Render Action Metadata
        run: |
          ./bin/render_action_metadata Dockerfile > action.yml

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test"
