name: 'Test'

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
  pull_request:
    paths-ignore:
      - 'README.md'

jobs:
  test-simple:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: simple
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test-${TEST_NAME}"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test-${TEST_NAME}"

  test-mojombo:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: mojombo
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test-${TEST_NAME}"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test-${TEST_NAME}"

  test-themes:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: themes
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test-${TEST_NAME}"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test-${TEST_NAME}"

  test-electronjs:
    runs-on: ubuntu-latest
    env:
      TEST_NAME: themes
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Test ${{ env.TEST_NAME }} Project
        uses: ./
        with:
          source: ./test_projects/${{ env.TEST_NAME }}
          destination: ./test_projects/${{ env.TEST_NAME }}/_site

      - name: Save test results
        run: |
          GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          git checkout -b "${GIT_BRANCH}-test-${TEST_NAME}"
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ${{ github.workspace }}/test_projects
          git commit -m "Test results: $(date)" || true
          git push -fu origin "${GIT_BRANCH}-test-${TEST_NAME}"
